language: go
go:
  - 1.11.x
  - 1.12.x
compiler:
  - g++
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libtesseract-dev libleptonica-dev tesseract-ocr-eng
env:
  - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
install:
  - go get -t -v ./...
script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
after_success:
    - bash <(curl -s https://codecov.io/bash)
