definitions:
  gin.H:
    additionalProperties: true
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/ocr/file:
    post:
      consumes:
      - application/json
      parameters:
      - description: file request
        in: formData
        name: payload
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: OCR识别整张上传的图片
      tags:
      - ocr
swagger: "2.0"
